import StressTensor.CKSecondDerivatives

/-!
# A geometric convergence certificate for the CK coefficient array

This file isolates a concrete last-mile criterion for turning the formal
two-variable CK coefficients into a `C²` function.  If the ordinary Taylor
coefficients satisfy a product-geometric estimate

`|a m n| ≤ M * sx^m * sy^n`,

then the series itself and all first and second derivative series used by the
normal-form equation converge absolutely on every strictly smaller box
`sx * rx < 1`, `sy * ry < 1`.

The theorem is intentionally a convergence *certificate*.  Establishing the
displayed estimate for the coefficients generated by the nonlinear CK
recursion is a separate majorant argument.
-/

namespace StressTensor

namespace CKGeometricMajorant

open CKPowerSeries CKSecondDerivatives

noncomputable section

/-- A separable product-geometric bound for ordinary Taylor coefficients. -/
structure GeometricBound (a : Coeff) (M sx sy : ℝ) : Prop where
  M_nonneg : 0 ≤ M
  sx_nonneg : 0 ≤ sx
  sy_nonneg : 0 ≤ sy
  bound : ∀ m n, |a m n| ≤ M * sx ^ m * sy ^ n

/-- A nonnegative product of two summable real sequences is summable on
`\mathbb N \times \mathbb N`. -/
private theorem summable_separable_product
    {u v : ℕ → ℝ} (hu : Summable u) (hv : Summable v)
    (hu0 : ∀ m, 0 ≤ u m) (hv0 : ∀ n, 0 ≤ v n) :
    Summable (fun p : ℕ × ℕ => u p.1 * v p.2) := by
  rw [summable_prod_of_nonneg]
  · constructor
    · intro m
      exact hv.mul_left (u m)
    · have hout : Summable (fun m => u m * ∑' n, v n) :=
        hu.mul_right (∑' n, v n)
      apply hout.congr
      intro m
      exact (hv.tsum_mul_left (u m)).symm
  · intro p
    exact mul_nonneg (hu0 p.1) (hv0 p.2)

/-- The scalar geometric sequence is summable at a nonnegative ratio below
one. -/
private theorem summable_weight_zero {s r : ℝ}
    (hs : 0 ≤ s) (hr : 0 ≤ r) (hsr : s * r < 1) :
    Summable (fun n : ℕ => s ^ n * r ^ n) := by
  have hnorm : ‖s * r‖ < 1 := by
    rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hs hr)]
    exact hsr
  simpa only [mul_pow] using
    (summable_geometric_of_norm_lt_one (x := s * r) hnorm)

/-- One differentiated geometric sequence is still summable strictly inside
its radius. -/
private theorem summable_weight_one {s r : ℝ}
    (hs : 0 ≤ s) (hr : 0 < r) (hsr : s * r < 1) :
    Summable (fun n : ℕ => (n : ℝ) * s ^ n * r ^ (n - 1)) := by
  apply (summable_nat_add_iff (f := fun n : ℕ =>
    (n : ℝ) * s ^ n * r ^ (n - 1)) 1).mp
  have hnorm : ‖s * r‖ < 1 := by
    rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hs hr.le)]
    exact hsr
  have hgeom : Summable (fun n : ℕ => (s * r) ^ n) :=
    summable_geometric_of_norm_lt_one hnorm
  have hlinear : Summable (fun n : ℕ => (n : ℝ) * (s * r) ^ n) := by
    simpa using summable_pow_mul_geometric_of_norm_lt_one (R := ℝ) 1 hnorm
  have hsum : Summable (fun n : ℕ =>
      s * ((n : ℝ) * (s * r) ^ n + (s * r) ^ n)) :=
    (hlinear.add hgeom).mul_left s
  apply hsum.congr
  intro n
  push_cast
  simp only [mul_pow, pow_succ]
  ring

/-- Two differentiated geometric sequences are still summable strictly
inside their radius. -/
private theorem summable_weight_two {s r : ℝ}
    (hs : 0 ≤ s) (hr : 0 < r) (hsr : s * r < 1) :
    Summable (fun n : ℕ =>
      (n : ℝ) * ((n - 1 : ℕ) : ℝ) * s ^ n * r ^ (n - 2)) := by
  apply (summable_nat_add_iff (f := fun n : ℕ =>
    (n : ℝ) * ((n - 1 : ℕ) : ℝ) * s ^ n * r ^ (n - 2)) 2).mp
  have hnorm : ‖s * r‖ < 1 := by
    rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hs hr.le)]
    exact hsr
  have hgeom : Summable (fun n : ℕ => (s * r) ^ n) :=
    summable_geometric_of_norm_lt_one hnorm
  have hlinear : Summable (fun n : ℕ => (n : ℝ) * (s * r) ^ n) := by
    simpa using summable_pow_mul_geometric_of_norm_lt_one (R := ℝ) 1 hnorm
  have hquad : Summable (fun n : ℕ => (n : ℝ) ^ 2 * (s * r) ^ n) :=
    summable_pow_mul_geometric_of_norm_lt_one (R := ℝ) 2 hnorm
  have hpoly : Summable (fun n : ℕ =>
      (n : ℝ) ^ 2 * (s * r) ^ n +
        3 * ((n : ℝ) * (s * r) ^ n) + 2 * (s * r) ^ n) :=
    (hquad.add (hlinear.mul_left 3)).add (hgeom.mul_left 2)
  have hsum := hpoly.mul_left (s ^ 2)
  apply hsum.congr
  intro n
  push_cast
  rw [pow_add]
  simp only [mul_pow]
  ring

/-- Product-geometric bounds imply absolute summability of the series on a
strictly smaller box. -/
theorem GeometricBound.summableOnBox
    {a : Coeff} {M sx sy rx ry : ℝ} (h : GeometricBound a M sx sy)
    (hrx : 0 ≤ rx) (hry : 0 ≤ ry)
    (hx : sx * rx < 1) (hy : sy * ry < 1) :
    SummableOnBox a rx ry := by
  have hsx := summable_weight_zero h.sx_nonneg hrx hx
  have hsy := summable_weight_zero h.sy_nonneg hry hy
  have hrow : ∀ m, Summable (fun n : ℕ => |a m n| * ry ^ n) := by
    intro m
    have hmajor : Summable (fun n : ℕ =>
        (M * sx ^ m) * (sy ^ n * ry ^ n)) :=
      hsy.mul_left (M * sx ^ m)
    exact hmajor.of_norm_bounded fun n => by
      rw [Real.norm_eq_abs, abs_of_nonneg
        (mul_nonneg (abs_nonneg _) (pow_nonneg hry _))]
      calc
        |a m n| * ry ^ n ≤ (M * sx ^ m * sy ^ n) * ry ^ n := by
          exact mul_le_mul_of_nonneg_right (h.bound m n) (pow_nonneg hry n)
        _ = (M * sx ^ m) * (sy ^ n * ry ^ n) := by ring
  constructor
  · exact hrow
  · have hmajorProd : Summable (fun p : ℕ × ℕ =>
        (M * (sx ^ p.1 * rx ^ p.1)) * (sy ^ p.2 * ry ^ p.2)) := by
      apply summable_separable_product
        (hsx.mul_left M) hsy
      · intro m
        exact mul_nonneg h.M_nonneg
          (mul_nonneg (pow_nonneg h.sx_nonneg _) (pow_nonneg hrx _))
      · intro n
        exact mul_nonneg (pow_nonneg h.sy_nonneg _) (pow_nonneg hry _)
    have htarget : Summable (fun p : ℕ × ℕ =>
        |a p.1 p.2| * ry ^ p.2 * rx ^ p.1) := by
      exact hmajorProd.of_norm_bounded fun p => by
        rw [Real.norm_eq_abs, abs_of_nonneg
          (mul_nonneg
            (mul_nonneg (abs_nonneg _) (pow_nonneg hry _))
            (pow_nonneg hrx _))]
        calc
          |a p.1 p.2| * ry ^ p.2 * rx ^ p.1 ≤
              (M * sx ^ p.1 * sy ^ p.2) * ry ^ p.2 * rx ^ p.1 := by
            gcongr
            exact h.bound p.1 p.2
          _ = (M * (sx ^ p.1 * rx ^ p.1)) *
                (sy ^ p.2 * ry ^ p.2) := by ring
    have hout := (summable_prod_of_nonneg (f := fun p : ℕ × ℕ =>
      |a p.1 p.2| * ry ^ p.2 * rx ^ p.1)
      (by intro p; positivity)).mp htarget |>.2
    apply hout.congr
    intro m
    change (∑' n : ℕ, |a m n| * ry ^ n * rx ^ m) =
      absRowSum a m ry * rx ^ m
    exact (hrow m).tsum_mul_right (rx ^ m)

/-- The same geometric certificate supplies the first `x` derivative
summability condition. -/
theorem GeometricBound.summableXDerivativeOnBox
    {a : Coeff} {M sx sy rx ry : ℝ} (h : GeometricBound a M sx sy)
    (hrx : 0 < rx) (hry : 0 ≤ ry)
    (hx : sx * rx < 1) (hy : sy * ry < 1) :
    SummableXDerivativeOnBox a rx ry := by
  have hbase := h.summableOnBox hrx.le hry hx hy
  have hsx := summable_weight_one h.sx_nonneg hrx hx
  have hsy := summable_weight_zero h.sy_nonneg hry hy
  have hmajorProd : Summable (fun p : ℕ × ℕ =>
      (M * ((p.1 : ℝ) * sx ^ p.1 * rx ^ (p.1 - 1))) *
        (sy ^ p.2 * ry ^ p.2)) := by
    apply summable_separable_product (hsx.mul_left M) hsy
    · intro m
      exact mul_nonneg h.M_nonneg
        (mul_nonneg
          (mul_nonneg (Nat.cast_nonneg _) (pow_nonneg h.sx_nonneg _))
          (pow_nonneg hrx.le _))
    · intro n
      exact mul_nonneg (pow_nonneg h.sy_nonneg _) (pow_nonneg hry _)
  have htarget : Summable (fun p : ℕ × ℕ =>
      (p.1 : ℝ) * |a p.1 p.2| * ry ^ p.2 * rx ^ (p.1 - 1)) := by
    exact hmajorProd.of_norm_bounded fun p => by
      rw [Real.norm_eq_abs, abs_of_nonneg (by positivity :
        0 ≤ (p.1 : ℝ) * |a p.1 p.2| * ry ^ p.2 * rx ^ (p.1 - 1))]
      calc
        (p.1 : ℝ) * |a p.1 p.2| * ry ^ p.2 * rx ^ (p.1 - 1) ≤
            (p.1 : ℝ) * (M * sx ^ p.1 * sy ^ p.2) *
              ry ^ p.2 * rx ^ (p.1 - 1) := by
          gcongr
          exact h.bound p.1 p.2
        _ = (M * ((p.1 : ℝ) * sx ^ p.1 * rx ^ (p.1 - 1))) *
              (sy ^ p.2 * ry ^ p.2) := by ring
  have hout := (summable_prod_of_nonneg (f := fun p : ℕ × ℕ =>
    (p.1 : ℝ) * |a p.1 p.2| * ry ^ p.2 * rx ^ (p.1 - 1))
    (by intro p; positivity)).mp htarget |>.2
  apply hout.congr
  intro m
  change (∑' n : ℕ,
      (m : ℝ) * |a m n| * ry ^ n * rx ^ (m - 1)) =
    (m : ℝ) * absRowSum a m ry * rx ^ (m - 1)
  calc
    (∑' n : ℕ, (m : ℝ) * |a m n| * ry ^ n * rx ^ (m - 1)) =
        ∑' n : ℕ, (|a m n| * ry ^ n) * ((m : ℝ) * rx ^ (m - 1)) := by
          apply tsum_congr
          intro n
          ring
    _ = absRowSum a m ry * ((m : ℝ) * rx ^ (m - 1)) := by
      exact (hbase.row m).tsum_mul_right ((m : ℝ) * rx ^ (m - 1))
    _ = (m : ℝ) * absRowSum a m ry * rx ^ (m - 1) := by ring

/-- The same geometric certificate supplies the first `y` derivative
summability condition. -/
theorem GeometricBound.summableYDerivativeOnBox
    {a : Coeff} {M sx sy rx ry : ℝ} (h : GeometricBound a M sx sy)
    (hrx : 0 ≤ rx) (hry : 0 < ry)
    (hx : sx * rx < 1) (hy : sy * ry < 1) :
    SummableYDerivativeOnBox a rx ry := by
  have hsx := summable_weight_zero h.sx_nonneg hrx hx
  have hsy := summable_weight_one h.sy_nonneg hry hy
  have hrow : ∀ m, Summable (fun n : ℕ =>
      |(n : ℝ) * a m n| * ry ^ (n - 1)) := by
    intro m
    have hmajor : Summable (fun n : ℕ =>
        (M * sx ^ m) * ((n : ℝ) * sy ^ n * ry ^ (n - 1))) :=
      hsy.mul_left (M * sx ^ m)
    exact hmajor.of_norm_bounded fun n => by
      rw [Real.norm_eq_abs, abs_of_nonneg (by positivity :
        0 ≤ |(n : ℝ) * a m n| * ry ^ (n - 1))]
      rw [abs_mul, abs_of_nonneg (Nat.cast_nonneg n)]
      calc
        (n : ℝ) * |a m n| * ry ^ (n - 1) ≤
            (n : ℝ) * (M * sx ^ m * sy ^ n) * ry ^ (n - 1) := by
          gcongr
          exact h.bound m n
        _ = (M * sx ^ m) * ((n : ℝ) * sy ^ n * ry ^ (n - 1)) := by ring
  constructor
  · exact hrow
  · have hmajorProd : Summable (fun p : ℕ × ℕ =>
        (M * (sx ^ p.1 * rx ^ p.1)) *
          ((p.2 : ℝ) * sy ^ p.2 * ry ^ (p.2 - 1))) := by
      apply summable_separable_product (hsx.mul_left M) hsy
      · intro m
        exact mul_nonneg h.M_nonneg
          (mul_nonneg (pow_nonneg h.sx_nonneg _) (pow_nonneg hrx _))
      · intro n
        exact mul_nonneg
          (mul_nonneg (Nat.cast_nonneg _) (pow_nonneg h.sy_nonneg _))
          (pow_nonneg hry.le _)
    have htarget : Summable (fun p : ℕ × ℕ =>
        |(p.2 : ℝ) * a p.1 p.2| * ry ^ (p.2 - 1) * rx ^ p.1) := by
      exact hmajorProd.of_norm_bounded fun p => by
        rw [Real.norm_eq_abs, abs_of_nonneg (by positivity :
          0 ≤ |(p.2 : ℝ) * a p.1 p.2| * ry ^ (p.2 - 1) * rx ^ p.1)]
        rw [abs_mul, abs_of_nonneg (Nat.cast_nonneg p.2)]
        calc
          (p.2 : ℝ) * |a p.1 p.2| * ry ^ (p.2 - 1) * rx ^ p.1 ≤
              (p.2 : ℝ) * (M * sx ^ p.1 * sy ^ p.2) *
                ry ^ (p.2 - 1) * rx ^ p.1 := by
            gcongr
            exact h.bound p.1 p.2
          _ = (M * (sx ^ p.1 * rx ^ p.1)) *
                ((p.2 : ℝ) * sy ^ p.2 * ry ^ (p.2 - 1)) := by ring
    have hout := (summable_prod_of_nonneg (f := fun p : ℕ × ℕ =>
      |(p.2 : ℝ) * a p.1 p.2| * ry ^ (p.2 - 1) * rx ^ p.1)
      (by intro p; positivity)).mp htarget |>.2
    apply hout.congr
    intro m
    change (∑' n : ℕ,
      |(n : ℝ) * a m n| * ry ^ (n - 1) * rx ^ m) =
      absYDerivativeRowSum a m ry * rx ^ m
    exact (hrow m).tsum_mul_right (rx ^ m)

/-- The geometric certificate supplies all three second-derivative
summability conditions. -/
theorem GeometricBound.summableSecondDerivativesOnBox
    {a : Coeff} {M sx sy rx ry : ℝ} (h : GeometricBound a M sx sy)
    (hrx : 0 < rx) (hry : 0 < ry)
    (hx : sx * rx < 1) (hy : sy * ry < 1) :
    SummableXXDerivativeOnBox a rx ry ∧
      SummableXYDerivativeOnBox a rx ry ∧
      SummableYYDerivativeOnBox a rx ry := by
  have hbase := h.summableOnBox hrx.le hry.le hx hy
  have hdy := h.summableYDerivativeOnBox hrx.le hry hx hy
  have hsx0 := summable_weight_zero h.sx_nonneg hrx.le hx
  have hsx1 := summable_weight_one h.sx_nonneg hrx hx
  have hsx2 := summable_weight_two h.sx_nonneg hrx hx
  have hsy0 := summable_weight_zero h.sy_nonneg hry.le hy
  have hsy1 := summable_weight_one h.sy_nonneg hry hy
  have hsy2 := summable_weight_two h.sy_nonneg hry hy
  constructor
  · have hmajorProd : Summable (fun p : ℕ × ℕ =>
        (M * ((p.1 : ℝ) * ((p.1 - 1 : ℕ) : ℝ) *
          sx ^ p.1 * rx ^ (p.1 - 2))) * (sy ^ p.2 * ry ^ p.2)) := by
      apply summable_separable_product (hsx2.mul_left M) hsy0
      · intro m
        exact mul_nonneg h.M_nonneg
          (mul_nonneg
            (mul_nonneg
              (mul_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _))
              (pow_nonneg h.sx_nonneg _))
            (pow_nonneg hrx.le _))
      · intro n
        exact mul_nonneg (pow_nonneg h.sy_nonneg _) (pow_nonneg hry.le _)
    have htarget : Summable (fun p : ℕ × ℕ =>
        (p.1 : ℝ) * ((p.1 - 1 : ℕ) : ℝ) * |a p.1 p.2| *
          ry ^ p.2 * rx ^ (p.1 - 2)) := by
      exact hmajorProd.of_norm_bounded fun p => by
        rw [Real.norm_eq_abs, abs_of_nonneg (by positivity :
          0 ≤ (p.1 : ℝ) * ((p.1 - 1 : ℕ) : ℝ) * |a p.1 p.2| *
            ry ^ p.2 * rx ^ (p.1 - 2))]
        calc
          (p.1 : ℝ) * ((p.1 - 1 : ℕ) : ℝ) * |a p.1 p.2| *
              ry ^ p.2 * rx ^ (p.1 - 2) ≤
            (p.1 : ℝ) * ((p.1 - 1 : ℕ) : ℝ) *
              (M * sx ^ p.1 * sy ^ p.2) * ry ^ p.2 * rx ^ (p.1 - 2) := by
              gcongr
              exact h.bound p.1 p.2
          _ = (M * ((p.1 : ℝ) * ((p.1 - 1 : ℕ) : ℝ) *
                sx ^ p.1 * rx ^ (p.1 - 2))) * (sy ^ p.2 * ry ^ p.2) := by ring
    have hout := (summable_prod_of_nonneg (f := fun p : ℕ × ℕ =>
      (p.1 : ℝ) * ((p.1 - 1 : ℕ) : ℝ) * |a p.1 p.2| *
        ry ^ p.2 * rx ^ (p.1 - 2)) (by intro p; positivity)).mp htarget |>.2
    apply hout.congr
    intro m
    change (∑' n : ℕ,
      (m : ℝ) * ((m - 1 : ℕ) : ℝ) * |a m n| * ry ^ n *
        rx ^ (m - 2)) =
      (m : ℝ) * ((m - 1 : ℕ) : ℝ) * absRowSum a m ry *
        rx ^ (m - 2)
    calc
      (∑' n : ℕ,
        (m : ℝ) * ((m - 1 : ℕ) : ℝ) * |a m n| * ry ^ n *
          rx ^ (m - 2)) =
        ∑' n : ℕ, (|a m n| * ry ^ n) *
          ((m : ℝ) * ((m - 1 : ℕ) : ℝ) * rx ^ (m - 2)) := by
            apply tsum_congr
            intro n
            ring
      _ = absRowSum a m ry *
          ((m : ℝ) * ((m - 1 : ℕ) : ℝ) * rx ^ (m - 2)) := by
        exact (hbase.row m).tsum_mul_right
          ((m : ℝ) * ((m - 1 : ℕ) : ℝ) * rx ^ (m - 2))
      _ = (m : ℝ) * ((m - 1 : ℕ) : ℝ) * absRowSum a m ry *
          rx ^ (m - 2) := by ring
  constructor
  · have hmajorProd : Summable (fun p : ℕ × ℕ =>
        (M * ((p.1 : ℝ) * sx ^ p.1 * rx ^ (p.1 - 1))) *
          ((p.2 : ℝ) * sy ^ p.2 * ry ^ (p.2 - 1))) := by
      apply summable_separable_product (hsx1.mul_left M) hsy1
      · intro m
        exact mul_nonneg h.M_nonneg
          (mul_nonneg
            (mul_nonneg (Nat.cast_nonneg _) (pow_nonneg h.sx_nonneg _))
            (pow_nonneg hrx.le _))
      · intro n
        exact mul_nonneg
          (mul_nonneg (Nat.cast_nonneg _) (pow_nonneg h.sy_nonneg _))
          (pow_nonneg hry.le _)
    have htarget : Summable (fun p : ℕ × ℕ =>
        (p.1 : ℝ) * |(p.2 : ℝ) * a p.1 p.2| *
          ry ^ (p.2 - 1) * rx ^ (p.1 - 1)) := by
      exact hmajorProd.of_norm_bounded fun p => by
        rw [Real.norm_eq_abs, abs_of_nonneg (by positivity :
          0 ≤ (p.1 : ℝ) * |(p.2 : ℝ) * a p.1 p.2| *
            ry ^ (p.2 - 1) * rx ^ (p.1 - 1))]
        rw [abs_mul, abs_of_nonneg (Nat.cast_nonneg p.2)]
        calc
          (p.1 : ℝ) * ((p.2 : ℝ) * |a p.1 p.2|) *
              ry ^ (p.2 - 1) * rx ^ (p.1 - 1) ≤
            (p.1 : ℝ) * ((p.2 : ℝ) *
              (M * sx ^ p.1 * sy ^ p.2)) * ry ^ (p.2 - 1) *
                rx ^ (p.1 - 1) := by
              gcongr
              exact h.bound p.1 p.2
          _ = (M * ((p.1 : ℝ) * sx ^ p.1 * rx ^ (p.1 - 1))) *
                ((p.2 : ℝ) * sy ^ p.2 * ry ^ (p.2 - 1)) := by ring
    have hout := (summable_prod_of_nonneg (f := fun p : ℕ × ℕ =>
      (p.1 : ℝ) * |(p.2 : ℝ) * a p.1 p.2| *
        ry ^ (p.2 - 1) * rx ^ (p.1 - 1))
      (by intro p; positivity)).mp htarget |>.2
    apply hout.congr
    intro m
    change (∑' n : ℕ,
      (m : ℝ) * |(n : ℝ) * a m n| * ry ^ (n - 1) * rx ^ (m - 1)) =
      (m : ℝ) * absYDerivativeRowSum a m ry * rx ^ (m - 1)
    calc
      (∑' n : ℕ,
        (m : ℝ) * |(n : ℝ) * a m n| * ry ^ (n - 1) *
          rx ^ (m - 1)) =
        ∑' n : ℕ, (|(n : ℝ) * a m n| * ry ^ (n - 1)) *
          ((m : ℝ) * rx ^ (m - 1)) := by
            apply tsum_congr
            intro n
            ring
      _ = absYDerivativeRowSum a m ry * ((m : ℝ) * rx ^ (m - 1)) := by
        exact (hdy.row m).tsum_mul_right ((m : ℝ) * rx ^ (m - 1))
      _ = (m : ℝ) * absYDerivativeRowSum a m ry * rx ^ (m - 1) := by ring
  · have hrow : ∀ m, Summable (fun n : ℕ =>
        |(n : ℝ) * ((n - 1 : ℕ) : ℝ) * a m n| * ry ^ (n - 2)) := by
      intro m
      have hmajor : Summable (fun n : ℕ =>
          (M * sx ^ m) * ((n : ℝ) * ((n - 1 : ℕ) : ℝ) *
            sy ^ n * ry ^ (n - 2))) := hsy2.mul_left (M * sx ^ m)
      exact hmajor.of_norm_bounded fun n => by
        rw [Real.norm_eq_abs, abs_of_nonneg (by positivity :
          0 ≤ |(n : ℝ) * ((n - 1 : ℕ) : ℝ) * a m n| * ry ^ (n - 2))]
        rw [abs_mul, abs_mul, abs_of_nonneg (Nat.cast_nonneg n),
          abs_of_nonneg (Nat.cast_nonneg (n - 1))]
        calc
          (n : ℝ) * ((n - 1 : ℕ) : ℝ) * |a m n| * ry ^ (n - 2) ≤
              (n : ℝ) * ((n - 1 : ℕ) : ℝ) *
                (M * sx ^ m * sy ^ n) * ry ^ (n - 2) := by
            gcongr
            exact h.bound m n
          _ = (M * sx ^ m) * ((n : ℝ) * ((n - 1 : ℕ) : ℝ) *
                sy ^ n * ry ^ (n - 2)) := by ring
    constructor
    · exact hrow
    · have hmajorProd : Summable (fun p : ℕ × ℕ =>
          (M * (sx ^ p.1 * rx ^ p.1)) *
            ((p.2 : ℝ) * ((p.2 - 1 : ℕ) : ℝ) * sy ^ p.2 *
              ry ^ (p.2 - 2))) := by
        apply summable_separable_product (hsx0.mul_left M) hsy2
        · intro m
          exact mul_nonneg h.M_nonneg
            (mul_nonneg (pow_nonneg h.sx_nonneg _) (pow_nonneg hrx.le _))
        · intro n
          exact mul_nonneg
            (mul_nonneg
              (mul_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _))
              (pow_nonneg h.sy_nonneg _))
            (pow_nonneg hry.le _)
      have htarget : Summable (fun p : ℕ × ℕ =>
          |(p.2 : ℝ) * ((p.2 - 1 : ℕ) : ℝ) * a p.1 p.2| *
            ry ^ (p.2 - 2) * rx ^ p.1) := by
        exact hmajorProd.of_norm_bounded fun p => by
          rw [Real.norm_eq_abs, abs_of_nonneg (by positivity :
            0 ≤ |(p.2 : ℝ) * ((p.2 - 1 : ℕ) : ℝ) * a p.1 p.2| *
              ry ^ (p.2 - 2) * rx ^ p.1)]
          rw [abs_mul, abs_mul, abs_of_nonneg (Nat.cast_nonneg p.2),
            abs_of_nonneg (Nat.cast_nonneg (p.2 - 1))]
          calc
            (p.2 : ℝ) * ((p.2 - 1 : ℕ) : ℝ) * |a p.1 p.2| *
                ry ^ (p.2 - 2) * rx ^ p.1 ≤
              (p.2 : ℝ) * ((p.2 - 1 : ℕ) : ℝ) *
                (M * sx ^ p.1 * sy ^ p.2) * ry ^ (p.2 - 2) * rx ^ p.1 := by
                gcongr
                exact h.bound p.1 p.2
            _ = (M * (sx ^ p.1 * rx ^ p.1)) *
                  ((p.2 : ℝ) * ((p.2 - 1 : ℕ) : ℝ) * sy ^ p.2 *
                    ry ^ (p.2 - 2)) := by ring
      have hout := (summable_prod_of_nonneg (f := fun p : ℕ × ℕ =>
        |(p.2 : ℝ) * ((p.2 - 1 : ℕ) : ℝ) * a p.1 p.2| *
          ry ^ (p.2 - 2) * rx ^ p.1)
        (by intro p; positivity)).mp htarget |>.2
      apply hout.congr
      intro m
      change (∑' n : ℕ,
        |(n : ℝ) * ((n - 1 : ℕ) : ℝ) * a m n| * ry ^ (n - 2) *
          rx ^ m) = absYYDerivativeRowSum a m ry * rx ^ m
      exact (hrow m).tsum_mul_right (rx ^ m)

/-- A product-geometric estimate is one sufficient, checkable hypothesis for
all convergence obligations in the existing bivariate-series realization. -/
theorem GeometricBound.allSummability
    {a : Coeff} {M sx sy rx ry : ℝ} (h : GeometricBound a M sx sy)
    (hrx : 0 < rx) (hry : 0 < ry)
    (hx : sx * rx < 1) (hy : sy * ry < 1) :
    SummableOnBox a rx ry ∧
      SummableXDerivativeOnBox a rx ry ∧
      SummableYDerivativeOnBox a rx ry ∧
      SummableXXDerivativeOnBox a rx ry ∧
      SummableXYDerivativeOnBox a rx ry ∧
      SummableYYDerivativeOnBox a rx ry := by
  have hsecond := h.summableSecondDerivativesOnBox hrx hry hx hy
  exact ⟨h.summableOnBox hrx.le hry.le hx hy,
    h.summableXDerivativeOnBox hrx hry.le hx hy,
    h.summableYDerivativeOnBox hrx.le hry hx hy,
    hsecond.1, hsecond.2.1, hsecond.2.2⟩

end

end CKGeometricMajorant

end StressTensor
